import JSZip from 'jszip';
import { normalizeUrl } from './model.js';

const TEMPLATE_ROOT = '/extension-template';
const TEXT_FILES = [
  'manifest.json',
  'background.js',
  'popup.html',
  'popup.js',
  'editor.js',
  'settings.html',
  'settings.js',
  'marked.js',
  'turndown.js',
];
const BINARY_FILES = ['icons/icon16.png', 'icons/icon48.png', 'icons/icon128.png'];

function jsValue(value) {
  return JSON.stringify(String(value ?? ''));
}

function replaceDefault(source, key, value) {
  const pattern = new RegExp(`(${key}\\s*:\\s*)(['\"])(?:\\\\.|(?!\\2).)*\\2`);
  return source.replace(pattern, `$1${jsValue(value)}`);
}

function customizeManifest(source, state) {
  const manifest = JSON.parse(source);
  const origin = new URL(normalizeUrl(state.backendUrl)).origin;
  manifest.description = 'Queue Notes, Reminders, and Calendar events to your private Apple Queue backend';
  manifest.host_permissions = [`${origin}/*`];
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function customizeSettings(source, state) {
  let out = source.replaceAll("'https://dashboard.erinskidds.com'", jsValue(normalizeUrl(state.backendUrl)));
  out = replaceDefault(out, 'apiKey', state.apiKey);
  out = replaceDefault(out, 'defaultFolder', state.defNotes);
  out = replaceDefault(out, 'defaultList', state.defList);
  out = replaceDefault(out, 'defaultCalendar', state.defCal);
  out = out.replace(/(aiEnabled\s*:\s*)(?:true|false)/, `$1${Boolean(state.ai)}`);

  const endpoints = [
    state.notes && "      ['Notes', '/api/apple-notes']",
    state.reminders && "      ['Reminders', '/api/reminders']",
    state.calendar && "      ['Calendar', '/api/calendar']",
  ].filter(Boolean).join(',\n');
  out = out.replace(/    const endpoints = \[[\s\S]*?\n    \];/, `    const endpoints = [\n${endpoints}\n    ];`);
  return out;
}

function customizePopup(source, state) {
  let out = source.replaceAll("'https://dashboard.erinskidds.com'", jsValue(normalizeUrl(state.backendUrl)));
  out = replaceDefault(out, 'apiKey', state.apiKey);
  out = replaceDefault(out, 'defaultFolder', state.defNotes);
  out = replaceDefault(out, 'defaultList', state.defList);
  out = replaceDefault(out, 'defaultCalendar', state.defCal);
  out = out.replace(/(aiEnabled\s*:\s*)(?:true|false)/, `$1${Boolean(state.ai)}`);

  const firstType = state.notes ? 'note' : state.reminders ? 'reminder' : 'event';
  out = out.replace("let currentType = 'note';", `let currentType = '${firstType}';`);
  out = out.replace(/await setType\(\s*'note',\s*settings\s*\);/, `await setType(\n      '${firstType}',\n      settings\n    );`);
  return out;
}

function customizePopupHtml(source, state) {
  const disabled = [
    !state.notes && 'note',
    !state.reminders && 'reminder',
    !state.calendar && 'event',
  ].filter(Boolean);
  if (!disabled.length) return source;
  const css = disabled.map((type) => `.type-tab[data-type="${type}"] { display: none; }`).join('\n  ');
  return source.replace('</style>', `  ${css}\n</style>`);
}

function customizeSettingsHtml(source, state) {
  return source
    .replaceAll('https://dashboard.erinskidds.com', normalizeUrl(state.backendUrl))
    .replace('Leave as default unless you changed the server address.', 'This build was created for your Apple Queue backend. You can change it here later.')
    .replace('Find this in the Apple Notes / Reminders / Calendar pages on your dashboard under "Set up the iOS Shortcut". The same key works for all three.', 'This build already contains the key generated by the setup wizard. The same key is used by your iOS Shortcuts.')
    .replace('Uses your dashboard server at', 'Uses your Apple Queue backend at');
}

export function customizeExtensionFile(path, source, state) {
  if (path === 'manifest.json') return customizeManifest(source, state);
  if (path === 'background.js') return customizeSettings(source, state);
  if (path === 'popup.js') return customizePopup(source, state);
  if (path === 'popup.html') return customizePopupHtml(source, state);
  if (path === 'settings.js') return customizeSettings(source, state);
  if (path === 'settings.html') return customizeSettingsHtml(source, state);
  return source;
}

async function fetchTemplateFile(path, binary = false) {
  const response = await fetch(`${TEMPLATE_ROOT}/${path}`);
  if (!response.ok) throw new Error(`Could not load extension template file: ${path}`);
  return binary ? response.arrayBuffer() : response.text();
}

export async function buildExtensionZip(state) {
  const zip = new JSZip();
  const [textEntries, binaryEntries] = await Promise.all([
    Promise.all(TEXT_FILES.map(async (path) => [path, await fetchTemplateFile(path)])),
    Promise.all(BINARY_FILES.map(async (path) => [path, await fetchTemplateFile(path, true)])),
  ]);

  for (const [path, source] of textEntries) zip.file(path, customizeExtensionFile(path, source, state));
  for (const [path, bytes] of binaryEntries) zip.file(path, bytes);
  zip.file('APPLE-QUEUE-SETUP.txt', [
    'This custom Apple Queue extension was generated locally in your browser.',
    `Backend: ${normalizeUrl(state.backendUrl)}`,
    `Modules: ${['Notes', 'Reminders', 'Calendar'].filter((_, i) => [state.notes, state.reminders, state.calendar][i]).join(', ')}`,
    `Natural-language parsing: ${state.ai ? 'enabled' : 'disabled'}`,
    '',
    'Keep this ZIP private: it contains your Apple Queue API key.',
  ].join('\n'));

  return zip.generateAsync({ type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } });
}

export async function downloadExtension(state) {
  const blob = await buildExtensionZip(state);
  const url = URL.createObjectURL(blob);
  try {
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = 'apple-queue-custom.zip';
    anchor.click();
  } finally {
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
}
